#!/bin/bash
#
# Copyright (c) 2005 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details

# make fsck automatically fix problems at boot time.
sed -i -e 's/^FSCKFIX=no/FSCKFIX=yes/' /etc/default/rcS

debconf-get() { echo GET $1 | debconf-communicate | cut -d ' ' -f 2 ; }

# the value of the server URL is passed in as parameter #1
DI_URL=$(debconf-get local/di-url)

log() {
    logger -t install_script "$@"
}

echo 'debian-installer post-install "install_script" from http://hands.com/d-i/'
log 'debug: running debian-installer post-install "install_script" from http://hands.com/d-i/'

# apache.  hurrah.
apt-get -y install apache dnsutils ssmtp cron at logcheck

# mysql server. hurrah.
apt-get -y install mysql-server-4.1

# php4.  hurrah.
apt-get -y install php4 php4-mysql php4-odbc php4-curl php4-cli php4-cgi \
                   libapache-mod-php4 php-auth php-radius

# install webmin and allow access from thingy.  internal network.
apt-get -y install webmin-apache webmin-htaccess webmin-core webmin-mysql

sed -i -e 's/^allow=127.0.0.1/allow=127.0.0.1 172.20.0.0\/255.255.255.0 10.0.0.0\/255.0.0.0/' /etc/webmin/miniserv.conf
/etc/init.d/webmin restart

log 'debug: hands-wf-install_script exiting successfully'
exit 0
