#!/bin/sh
set -e

echo 'debug: Running...'

apt-install madwifi-source madwifi-tools gcc-4.0 wireless-tools
echo ath_pci > /target/etc/modules
echo "m-a --non-inter prepare; m-a --non-inter a-i madwifi; modprobe ath_pci" >> /target/root/.bash_history

echo "debug: completed successfully"
