#!/bin/bash
#
# Copyright (c) 2005-2006 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details
set -e

. /usr/share/debconf/confmodule
. /tmp/HandsOff-fn.sh

echo 'debug: Running...'

#==== /etc/hosts
db_get local/domain && localdom=$RET
[ -n "$localdom" ] || db_get netcfg/get_domain && localdom=$RET
db_get local/net/ifaces && iface=$(echo $RET|cut -d' ' -f1)
db_get local/net/$iface/ip && ip=$RET
db_get netcfg/get_hostname && hostname=$RET

sed -i 's#^127\.0\.0\.1.*#127.0.0.1 localhost.localdomain localhost\n'$ip' '$hostname'.'$localdom' '$hostname'#' /target/etc/hosts

#==== network/interfaces
# currently only works for thunderbird3
cat > /target/etc/network/interfaces <<!EOF!
# We always want the loopback interface. Whether we want ifup/ifdown to
# know about is another matter, perhaps.
#
auto lo
iface lo inet loopback
!EOF!

db_get local/net/ifaces && local ifaces=$RET
for iface in $ifaces ; do
  ip=ERROR ;    db_get local/net/$iface/ip &&    ip=$RET
  net=ERROR ;   db_get local/net/$iface/net &&   net=$RET
  nmask=ERROR ; db_get local/net/$iface/nmask && nmask=$RET
  bcast=ERROR ; db_get local/net/$iface/bcast && bcast=$RET
  cat >> /target/etc/network/interfaces <<-!EOF!

	#
	auto $iface
	iface $iface inet static
	     address $ip
	     network $net
	     netmask $nmask
	     broadcast $bcast
	!EOF!
  db_get local/net/eth$/gw && [ -n "$RET" ] && \
    echo "     gateway $RET" >> /target/etc/network/interfaces
done

echo "# --- EOF ---" >> /target/etc/network/interfaces

echo "debug: completed successfully"
