#!/bin/sh

# Copyright © 2013-2016 Daniel Dehennin <daniel.dehennin@baby-gnu.org>
#
# Distributed under the terms of the GNU GPL version 2 or (at your
# option) any later version see the file "COPYING" for details
#
# Environment variable: ${class}

set -e

. /tmp/HandsOff-fn.sh

echo "debug: Running..."

checkflag dbg/flags all-x late-x partman-x && set -x

# Remove spurious lv if any
db_get partman-auto-lvm/new_vg_name
if [ -n "${RET}" ]
then
    for lv in /dev/${RET}/keep*
    do
	checkflag dbg/pauses all late partman \
	    && pause "Removing logical volume “$lv”" 'Fallow LV removal'
	lvremove -f "${lv}"
    done
fi
