#!/bin/sh
#
# Copyright (c) 2005-2006 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details
set -e

. /usr/share/debconf/confmodule
. /tmp/HandsOff-fn.sh

echo "debug: Running..."

# get all the classes users, and use the one that's left at the end
for class in default $(classes); do
  preseed_fetch "/local/users/$class" /tmp/setup-users.users &&
    mv /tmp/setup-users.users /target/tmp
done

# grab all the mentioned ssh keys, ready for installation
for keyname in $(sed -ne '/^#/!s/^.*:\([^:]*\)$/\1/p' /target/tmp/setup-users.users | tr "," "\n" | sort -u)
do
  preseed_fetch "/local/users/sshkeys.$keyname" "/target/tmp/sshkeys.$keyname"
done

apt-install sudo

cat > /target/tmp/setup-users.pl <<'!EOF!'
#!/usr/bin/perl -w

$pwfile=shift;

while (<>) {
  chomp ;
  next if /^\s*(#|$)/ ;
  my ($user,$crypt,$sudoer,$gecos,$sshkeys) = split(':') ;

  open(APTCFG,">/etc/apt/apt.conf") || die;

  if ("root" ne "$user") {
    system("adduser --disabled-login --gecos \"$gecos\" $user") ;
  }

  system("sed -i -e 's#^${user}:!:#${user}:${crypt}:#' $pwfile") ;

  if ($sudoer) {
    open(SUDOERS,">>/etc/sudoers") ;
    printf SUDOERS "%s\tALL=(ALL) ALL\n", $user ;
    close(SUDOERS) ;
  }
  
  system("mkdir ~$user/.ssh") ;
  foreach my $key (split(',',$sshkeys)) {
    system("cat /tmp/sshkeys.$key >> ~$user/.ssh/authorized_keys") ;
  }
  system("chown -R $user: ~$user/.ssh") ;
}
!EOF!

pwfile=/etc/shadow
db_get mirror/suite && [ sarge = "$RET" ] && pwfile=/etc/passwd

chmod +x /target/tmp/setup-users.pl
in-target /tmp/setup-users.pl $pwfile /tmp/setup-users.users
rm /target/tmp/setup-users.* /target/tmp/sshkeys.*

echo "debug: ended successfully"
