#!/bin/sh
#
# Copyright (c) 2005 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details
set -e

. /usr/share/debconf/confmodule
. /tmp/HandsOff-fn.sh

echo "debug: Running..."

# discard spare LVM volume, freeing up the space for DomU volumes
db_get partman-auto-lvm/new_vg_name && VG_NAME=$RET
lvremove --force /dev/$VG_NAME/keep_2

db_get mirror/suite &&
  echo 'APT::Default-Release "'$RET'";' >> /target/etc/apt/apt.conf

# this bit is not very portable, and needs some work
XEN_VER=3.0.3-1
SUBARCH="$(archdetect)"
LINARCH=${SUBARCH%%/*}
XENARCH=$LINARCH
[ "i386" = $LINARCH ] && LINARCH=686
apt-install xen-hypervisor-$XEN_VER-$XENARCH-pae || apt-install xen-hypervisor-$XEN_VER-$XENARCH
apt-install xen-utils-$XEN_VER xen-docs-3.0
apt-install linux-image-2.6-xen-$LINARCH

# Xen doesn't play nice with TLS -- fixed in later packages
#apt-install libc6-xen || in-target mv /lib/tls /lib/tls.disabled

#XEN_KERNEL=$(echo /target/boot/vmlinuz-*-xen-*)
#XEN_KERN_VER=${XEN_KERNEL#*vmlinuz-}
#in-target mkinitramfs -o /boot/initrd.img-$XEN_KERN_VER $XEN_KERN_VER

# make a directory for disk image files, and make image (see files/cobble-initrd)
mkdir /target/home/xen-disks
preseed_fetch /classes/xen3/files/cobble-initrd  /target/home/xen-disks/cobble-initrd
preseed_fetch /classes/xen3/files/initrd.gz  /target/home/xen-disks/orig-netinst-initrd.gz
in-target sh /home/xen-disks/cobble-initrd /home/xen-disks/orig-netinst-initrd.gz /home/xen-disks/xen-netinst-initrd.gz

# set up config files
preseed_fetch /classes/xen3/files/xend-config.sxp  /target/etc/xen/xend-config.sxp
preseed_fetch /classes/xen3/files/xm-debinst1  /target/etc/xen/xm-debinst1
preseed_fetch /classes/xen3/files/xm-debinst1-install  /target/etc/xen/xm-debinst1-install

in-target sed -ie "s#XEN_VMLINUZ#$(echo /boot/vmlinuz-*xen*)#" /etc/xen/xm-debinst1-install
in-target sed -ie "s#XEN_VMLINUZ#$(echo /boot/vmlinuz-*xen*)#;s#XEN_INITRD#$(echo /boot/initrd.img-*xen*)#" /etc/xen/xm-debinst1

# sort out a bridge setup for Xen
apt-install bridge-utils
#sed -i 's/allow-hotplug eth0/auto br0/' /target/etc/network/interfaces
#sed -i 's/eth0/br0/' /target/etc/network/interfaces
#cat >> /target/etc/network/interfaces <<!EOF!
#	bridge_ports eth0
#	bridge_fd 1
#	bridge_hello 1
#	bridge_stp off
#!EOF!

# prepopulate root's history with commands needed to install a new xen domain
cat > /target/root/.bash_history <<!EOF!
 #dd if=/dev/zero of=/dev/hda count=1 ; sync ; reboot -f
lvcreate -L 2G -n vm1hda $VG_NAME
xm create -c xm-debinst1-install
xm create -c xm-debinst1
!EOF!
chmod 600 /target/root/.bash_history

checkflag dbg/pauses all xen3 && pause "End of Xen3 late_script"

echo "debug: completed successfully"
