#!/bin/sh
#
# Copyright (c) 2005 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details

MYNAME="classes/xen3/late_script"

. /usr/share/debconf/confmodule
. /tmp/HandsOff-fn.sh

log "debug: Running..."

echo 'APT::Default-Release "stable";' >> /target/etc/apt/apt.conf

apt-install xen-hypervisor-3.0-i386 xen-utils-3.0 xen-docs-3.0
apt-install linux-image-xen-686 || apt-install linux-image-2.6.16-2-xen-686

# Xen doesn't play nice with TLS
apt-install libc6-xen || in-target mv /lib/tls /lib/tls.disabled

XEN_KERNEL=$(echo /target/boot/vmlinuz-2.6.16-2-xen-686)
XEN_VER=${XEN_KERNEL#*vmlinuz-}
in-target mkinitramfs -o /boot/initrd.img-$XEN_VER $XEN_VER

# put Xen into grub
XEN=$(cd /target/boot; ls xen*.gz|head -1)
ROOTDEV=$(sed -ne 's#^\([^	 ]*\)[	 ]*/[	 ].*$#\1#p' /target/etc/fstab)
sed -ie '/### BEGIN AUTOMAGIC KERNELS LIST/i\
title Xen 3\
  kernel /boot/'"$XEN"' dom0_mem=64000\
  module  /boot/vmlinuz-'"$XEN_VER"' root='"$ROOTDEV"' ro\
  module  /boot/initrd.img-'"$XEN_VER"'\
' /target/boot/grub/menu.lst

# make a directory for disk image files, and make image (see files/cobble-initrd)
mkdir /target/home/xen-disks
preseed_fetch /classes/xen3/files/cobble-initrd  /target/home/xen-disks/cobble-initrd
preseed_fetch /classes/xen3/files/initrd.gz  /target/home/xen-disks/orig-netinst-initrd.gz
in-target sh /home/xen-disks/cobble-initrd /home/xen-disks/orig-netinst-initrd.gz /home/xen-disks/xen-netinst-initrd.gz

# set up config files
preseed_fetch /classes/xen3/files/xend-config.sxp  /target/etc/xen/xend-config.sxp
preseed_fetch /classes/xen3/files/xm-debinst1  /target/etc/xen/xm-debinst1
preseed_fetch /classes/xen3/files/xm-debinst1-install  /target/etc/xen/xm-debinst1-install

# sort out the LVM partition
# First, unmount the redundant partition
umount /target/reserved-for-LVM
# then change the big partition's type to LVM
echo -e 't\n6\n8e\nw\nq' | fdisk /dev/discs/disc0/disc
# then get rid of the offending line in the fstab, after remembering the device
LVMDEV=$(sed -ne 's#^\([^	 ]*\)[	 ]*/reserved-for-LVM[	 ].*$#\1#p' /target/etc/fstab)
sed -ie '/reserved-for-LVM/d' /target/etc/fstab
# and discard the redundant mountpount
rmdir /target/reserved-for-LVM
# set up LVM
apt-install lvm2

# sort out a bridge setup for Xen
apt-install bridge-utils
#sed -i 's/allow-hotplug eth0/auto br0/' /target/etc/network/interfaces
#sed -i 's/eth0/br0/' /target/etc/network/interfaces
#cat >> /target/etc/network/interfaces <<!EOF!
#	bridge_ports eth0
#	bridge_fd 1
#	bridge_hello 1
#	bridge_stp off
#!EOF!

# prepopulate root's history with commands needed to install a new xen domain
cat > /target/root/.bash_history <<!EOF!
#dd if=/dev/zero of=/dev/hda count=1 ; sync ; reboot -f
pvcreate $LVMDEV
vgcreate vg $LVMDEV
lvcreate -L 2G -n vm1hda vg
xm create -c xm-debinst1-install
xm create -c xm-debinst1
!EOF!
chmod 600 /target/root/.bash_history

dbg_pause "End of Xen3 late_script" all xen3
log "debug: script ended successfully"
