#!/bin/bash

debconf-get() { echo GET $1 | debconf-communicate | cut -d ' ' -f 2 ; }

# the value of the server URL is passed in as parameter #1
di-url=$(debconf-get local/di-url)

log() {
    logger -t install_script "$@"
}

echo 'debian-installer post-install "install_script" from http://hands.com/d-i/'
log 'debug: running debian-installer post-install "install_script" from http://hands.com/d-i/'

# I'm lazy -- this lets me retry an install, by typing up-arrow return
echo "dd if=/dev/zero of=/dev/hda count=1 ; sync ; reboot -f" > /root/.bash_history
chmod 600 /root/.bash_history

# FIXME -- should never get loaded in the first place
# don't need these
apt-get -y remove mdetect read-edid

# install ssh, and stop root login by password --- no race condition if root has no password :-)
apt-get -y install ssh
sed -i -e 's/^PermitRootLogin *yes/PermitRootLogin without-password/' /etc/ssh/sshd_config
/etc/init.d/ssh restart
# can set a root password here reasonably safely

# FIXME -- make this check local/site
#since this is the default location, let's just set it empty
sed -i -e 's#^root:[^:]*:#root::#' /etc/shadow

# make sure we have md5sums for all packages we install
apt-get -y install debsums
cat >> /etc/apt/apt.conf <<!EOF!
DPkg::Post-Invoke {
        "debsums --generate=nocheck -sp /var/cache/apt/archives";
};
!EOF!

# nice stuff, even on a minmal box
apt-get -y install debconf-utils less udev sudo rsync debsums

# set LESSPIPE as I prefer
sed -i -e '/^  if \[ "$BASH" ]; then$/a\    . /etc/bash.bashrc' /etc/profile
echo "export LESSOPEN=\"|lesspipe '%s'\"" >> /etc/bash.bashrc

# lbwf-dns specifics
apt-get -y install bind9 apache dnsutils ssmtp cron at logcheck

# needed for the idswitch script
apt-get -y install libterm-prompt-perl libnet-dns-perl libnewt-perl
wget ${di-url}/site-files/hands-wf/idswitch -O /usr/local/sbin/idswitch
wget ${di-url}/misc/rsyncSend -O /usr/local/sbin/rsyncSend
chmod +x /usr/local/sbin/idswitch /usr/local/sbin/rsyncSend

# add users phil,adouse,backuppc
adduser --disabled-password --gecos 'Philip Hands,,,' phil
sed -i -e 's#^phil:[^:]*:#phil:$1$2CgaHWaR$Su66Oh7YUkJyAvlyI0hWS.:#' /etc/shadow
su phil 'mkdir ~phil/.ssh; grep phil@hands.com /root/.ssh/authorized_keys > ~phil/.ssh/authorized_keys'

adduser --disabled-password --gecos 'Andy Douse,,,' adouse
sed -i -e 's#^adouse:[^:]*:#adouse:$1$IZtseV66$SJrSvlGwUc2xcP0GjJK2a0:#' /etc/shadow
 
# user for backups, and matching key
adduser --system --gecos 'BackupPC,,,'i --shell /bin/sh backuppc
su backuppc 'mkdir ~/.ssh'

# /etc/sudoers
cat >> /etc/sudoers <<!EOF!
phil   ALL=(ALL) ALL
adouse ALL=(ALL) ALL

backuppc  ALL=NOPASSWD: /usr/local/sbin/rsyncSend
!EOF!

 
# edit ssmtp.conf
sed -i -e 's/^mailhub=.*$/mailhub=snoopy/' /etc/ssmtp/ssmtp.conf

#apt-get -y kernel?
# kernel-image-2.6.9-lbwf1u

cat >> /etc/bind/named.conf.local <<!EOF!
zone "lbwf.gov.uk" {
        type slave;
        file "db.lbwf";
       masters { 10.1.1.5 ; };
};

zone "10.in-addr.arpa" {
        type slave;
        file "db.10";
       masters { 10.1.1.5 ; };
};

zone "89.in-addr.arpa" {
        type slave;
        file "db.89";
       masters { 10.1.1.5 ; };
};

zone "12.85.212.in-addr.arpa" {
        type slave;
        file "db.212.85.12";
       masters { 10.1.1.5 ; };
};

zone "walthamforest.gov.uk" {
        type slave;
        file "db.walthamforest";
       masters { 10.1.1.5 ; };
};

!EOF!

# add our DNS forwarders in
sed -i -e '/forwarders *{/,/}/{
s#// *##
s/^.*0\.0\.0\.0;/\t\t10.1.1.5;\n\t\t10.1.16.203;/
}' /etc/bind/named.conf.options

# prompt to switch IP addresses
/usr/local/sbin/idswitch

log 'debug: lbwf-install_script exiting successfully'
exit 0
