#!/bin/sh
#
# Copyright (c) 2007 Luke Kenneth Casson Leighton <lkcl@lkcl.net>
#
# distributed under the terms of the GNU GPL version 2 or (at your option)
# any later version
# see the file "COPYING" for details
#
# some really cool 3D games.

set -e

. /tmp/HandsOff-fn.sh

echo 'debug: Running...'

apt-install --force-yes joystick jscalibrator flightgear bzflag \
	bzflag-server vdrift vdrift-full searchandrescue mednafen gngb fceu \
	visualboyadvance dgen xblast planetpenguin-racer

echo 'debug: exiting successfully'

exit 0
