#!/bin/sh
set -e

. /usr/share/debconf/confmodule

echo "debug: Running..."

db_get mirror/suite &&
  echo 'APT::Default-Release "'$RET'";' >> /target/etc/apt/apt.conf

# work-around for the fact that kolabd's packaging is currently a bit broken
cat >> /target/etc/apt/preferences <<!EOF!
Package: *
Pin: origin deasil.hands.com
Pin-Priority: 999
!EOF!

apt-install postfix/unstable postfix-ldap/unstable
apt-install kolabd kolab-webadmin kolabadmin

# lets have SSL stuff as well (this should be doable via the web interface, but isn't currently for some reason)
sed -ie 's/#\(imaps\|pop3s\)/\1/' /target/etc/cyrus.conf

# slapd (perhaps) needs to read the ssl certs, that belong to group mail
# There's probably a better way of doing this, and I'm not even sure that slapd needs this, so I'll comment it out for a while
#sed -ie 's/^mail:x:8:$/mail:x:8:openldap/' /target/etc/group


echo "debug: script ended successfully"
