#!/bin/sh
#
# Copyright (c) 2007 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details
set -e
echo "debug: Running..."
. /usr/share/debconf/confmodule
. /tmp/HandsOff-fn.sh

checkflag dbg/flags all-x koolu-x && set -x

#sed -ie 's/^# defoptions=.*/# defoptions=vga=791 splash quiet/' /target/boot/grub/menu.lst

apt-install linux-image-2.6.23.1-koolu \
  xserver-xorg-video-amd xserver-xorg discover libgl1-mesa-glx libgl1-mesa-dri libglu1-mesa \
  xfonts-base xfonts-100dpi xfonts-75dpi xfonts-scalable alsa-base alsa-utils \
  xresprobe cpufrequtils vbetool menu discover xresprobe mdetect read-edid xutils binutils xpdf \
  usplash usplash-theme-debian

# firefox and friends... pdf and flash
apt-install iceweasel x-ttcidfont-conf xprint  xprint-utils matchbox-window-manager mozplugger xpdf
apt-install iceweasel-l10n-* iceweasel-l10n-roa-es-val-

in-target tasksel install kde-desktop

sed -ie '/Section "Device"/a\        Option "NoCompression" "true"' /target/etc/X11/xorg.conf

apt-install prelink

in-target aptitude clean

# This takes _ages_ so might well be something to try and optimise
in-target prelink -q -v -a --conserve-memory --random

echo "debug: completed successfully"
