#!/bin/bash
#
# Copyright (c) 2005-2006 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details

MYNAME="hands.com-general-tweaks/install_script"

log() {
    logger -t install_script "$@"
}

echo 'd-i post-install "'$MYNAME'" from http://hands.com/d-i/'
log 'debug: running d-i post-install "'$MYNAME'" from http://hands.com/d-i/'

# make fsck automatically fix problems at boot time.
sed -i -e 's/^FSCKFIX=no/FSCKFIX=yes/' /etc/default/rcS

# set LESSPIPE as I prefer
sed -i -e '/^  if \[ "$BASH" ]; then$/a\    . /etc/bash.bashrc' /etc/profile
echo "export LESSOPEN=\"|lesspipe '%s'\"" >> /etc/bash.bashrc


log 'debug: '$MYNAME': exiting successfully'

exit 0
