#!/bin/sh
# 0-defaults preseed from http://hands.com/d-i/dsd/0-defaults
#
# Copyright (c) 2005-2006 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details
#

# here we put stuff that we often expect to override
d-i     languagechooser/language-name   string English
d-i     countrychooser/shortlist        string US
d-i     console-keymaps-at/keymap       string us
d-i     mirror/country                  string enter information manually
d-i     mirror/http/hostname            string ftp.debian.org
d-i     mirror/http/directory           string /debian
base-config     apt-setup/hostname      string ftp.debian.org
base-config     apt-setup/directory     string /debian

#=-=-=-=- bits that were once _common.cfg
# some basic configs, may be overridden by other files
d-i	mirror/suite			string stable
d-i	mirror/http/proxy		string
d-i	partman-auto/disk		string /dev/discs/disc0/disc
d-i	partman-auto/choose_recipe	select Multi-user workstation
d-i	partman/confirm_write_new_label boolean true
d-i	partman/choose_partition	select Finish partitioning and write changes to disk
d-i	partman/confirm			boolean true
d-i	grub-installer/only_debian	boolean true
d-i	prebaseconfig/reboot_in_progress	note

# This first command is run as early as possible, just after
# preseeding is read.
d-i preseed/early_command		string dsd_fetch_file dsd/early_script /tmp/early_script;sh -x /tmp/early_script ; > /var/log/early_script.out 2>&1

# and this gets run just before the /target is unmounted
d-i	preseed/late_command		string dsd_fetch_file dsd/late_script /tmp/late_script ; sh /tmp/late_script > /var/log/late_script.out 2>&1

base-config	base-config/intro	note 
base-config	base-config/login	note 
base-config	tzconfig/gmt		boolean true
passwd		passwd/make-user	boolean false
base-config	apt-setup/uri_type	select http
base-config	apt-setup/country	select enter information manually
base-config	apt-setup/another	boolean false
base-config	apt-setup/security-updates	boolean true
tasksel		tasksel/first		multiselect
# need a different approach to get values out of debconf after the reboot
d-i base-config/late_command string bash /var/tmp/base-config.late_command 2>&1 | tee /var/log/installer/base-config.late_command.out

ssh	ssh/protocol2_only	boolean true
ssh	ssh/run_sshd		boolean true
ssh	ssh/SUID_client		boolean false

# Joey says: For some reason this question is asked on hppa and a few other
# archs (due to serial console install?)
console-data console-data/keymap/policy select Don't touch keymap
#=-=-=-=-

d-i	preseed/run			string 0-early-dsd-setup.sh
