#!/bin/sh
#
# Copyright (c) 2005-2006 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details

log() {
    logger -t late_script "$@"
}
in_local_class() {
    echo "$(debconf-get dsd/classes)" | sed -e 's/;/\n/g' | grep -q "^$1\$"
}
local_classes() {
    echo "$(debconf-get dsd/classes)" | sed -e 's/;/\n/g'
}

log "debug: Running script from http://hands.com/d-i/dsd/late_script"
set -x

# let's see what was installed by the end of the run (copied to /var/log/debian-installer/ along with the other log files)
cp /var/lib/dpkg/status /var/log/dpkg-status

# lock the root login if there's no password to set
# (has the side effect of shutting up the root password prompt)
if [ "$(debconf-get passwd/root-password)" ]; then
  $(debconf-set passwd/root-password-again $(debconf-get passwd/root-password))
else
  sed -i -e 's#^root:[^:]*:#root:!:#' /target/etc/passwd
fi

# stuff values we may need in the install script into the next stages's preseed data
for i in classes di-url ; do
  echo dsd dsd/$i string $(debconf-get dsd/$i) >> /var/log/debconf-seed
done

# let's see if we're running under xen
if [ -e /proc/xen ] ; then
  mv /target/lib/tls /target/lib/tls.disabled
  # nasty hack, as we should probably install the kernel package
  cp -a /lib/modules/2.6.11-xenu /target/lib/modules/2.6.11-xenu
fi

# get install script so  that it's ready for the first boot, and we don't
# necisarilly need net access after the reboot (handy when changing IP addresses)
dsd_fetch_file dsd/install_script /target/var/tmp/base-config.late_command
chmod +x /target/var/tmp/base-config.late_command
target_parts_d=/target/var/tmp/base-config.late_command.d
mkdir ${target_parts_d}

# get all the classes install_scripts
for class in $(local_classes); do
  : $((x++)) # increment x each time round the loop
  target="${target_parts_d}/$(printf "%03d-%s" "$x" "$(echo ${class}|sed 's/\([^-a-zA-Z0-9]\)/_/g')")"
  dsd_fetch_file "dsd/${class}/install_script" "${target}" && \
    chmod +x "${target}"
done

### this is for debugging --- kill the sleep to continue
if in_local_class "sleeps" ; then
  sleep 10000 || true
fi

# chain onto class specific late_script(s) if any
for class in $(local_classes); do
  dsd_fetch_file dsd/${class}/late_script /tmp/late_script-${class} && \
    sh /tmp/late_script-${class} > /var/log/late_script-${class}.out 2>&1
done

log "debug: ended successfully"
