#!/bin/sh
#
# Copyright (c) 2005 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details

log() {
    logger -t late_script "$@"
}

log "debug: Running script from http://hands.com/d-i/site-files/default/type-files/xen0/preseed_late_script"
set -x

# First, unmount the redundant partition
umount /target/reserved-for-LVM

# then change the big partition's type to LVM
echo -e 't\n6\n8e\nw\nq' | fdisk /dev/discs/disc0/disc

# then get rid of the offending line in the fstab
sed -ie '/reserved-for-LVM/d' /target/etc/fstab

# and discard the redundant mountpount
rmdir /target/reserved-for-LVM

apt-install debootstrap python python2.3-twisted iproute bridge-utils libcurl3-dev

# set LESSPIPE as I prefer
in-target sed -i -e '/^  if \[ "$BASH" ]; then$/a\    . /etc/bash.bashrc' /etc/profile
echo "export LESSOPEN=\"|lesspipe '%s'\"" >> /target/etc/bash.bashrc

#echo 'deb http://packages.debianbase.de/sarge/i386/xen3 ./' >> /target/etc/apt/sources.list

in-target apt-get update
in-target apt-get -y xen linux-xen0-2.6
in-target dpkg -i /usr/src/*xen*.deb
in-target mkinitrd -o /boot/xen-modules-2.6.12.6-xen 2.6.12.6-xen

# put Xen into grub
ed /boot/grub/menu.lst 2>/dev/null <<EOF
/### BEGIN AUTOMAGIC KERNELS LIST/i
title Xen 3
  kernel /boot/xen.gz dom0_mem=64000
  module  /boot/xen-linux-2.6.12.6-xen root=/dev/hda1 ro
  module  /boot/xen-modules-2.6.12.6-xen' /target/boot/grub/menu.lst > /target/boot/grub/menu.tmp

.
w
q
EOF

apt-install lvm2
in-target pvcreate /dev/hda6
in-target vgcreate vg /dev/hda6
in-target lvcreate -L 2G -n vm1hda vg

# make a directory for disk image files
#mkdir /target/home/xen-disks
#dsd_fetch_file d-i/dsd/xen0/files/netboot-initrd.gz /target/home/xen-disks/net
boot-initrd.gz


log "debug: xen0 script ended successfully"
