#!/bin/sh
#
# Copyright (c) 2007 Luke Kenneth Casson Leighton <lkcl@lkcl.net>
#
# distributed under the terms of the GNU GPL version 2 or (at your option)
# any later version
# see the file "COPYING" for details
#
# network-manager is a pile of shit, and the developers who thought it
# was funny to design a system to run on a _unix_ platform, where everything
# is shoved into one fucked up binary-formatted blob which then controls
# something as utterly essential and vital as networking, should have their
# heads examined.
#
# fortunately, wicd has been designed as a reasonable replacement.
#
# we now proceed to install it from debian/testing, where it lives,
# but to avoid disrupting the whole point of reproducible stable
# unattended installs we have to use pinning.
#
# remember to add the "testing" archive to the top-level preseed
# NOT to the classes/desktop/wicd/preseed (copy the one commented out)
# so that you don't end up overwriting local0, local1, local2, local3
# etc. archives.

set -e

. /tmp/HandsOff-fn.sh

echo 'debug: Running...'

cat >> /target/etc/apt/preferences <<!EOF!
Package: *
Pin: release a=stable
Pin-Priority: 900
Package: *
Pin: release a=testing
Pin-Priority: 800
!EOF!


in-target apt-get --force-yes -y -t testing install wicd

# sudo is required but is _not_ added here, that must be done
# elsewhere because typically the /etc/sudoers file has to be
# done in one place.  see classes/desktop/kde/useability/late_scrit
# as an example, but something like this will be needed:
# %adm    ALL=NOPASSWD: /usr/bin/wicd-client

