#!/bin/sh
#
# Copyright (c) 2007 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details

set -e
echo "debug: Running koolu/splash/late_script..."
. /usr/share/debconf/confmodule
. /tmp/HandsOff-fn.sh

checkflag dbg/flags all-x koolu-splash-x && set -x

sed -i 's/^# defoptions=.*/# defoptions=vga=791 splash quiet/' /target/boot/grub/menu.lst

# Grub splash screen
preseed_fetch $CHECKSUM_IF_AVAIL /classes/koolu/files/koolu_splash.xpm.gz /target/boot/grub/koolu_splash.xpm.gz
sed -i '/^color/a \\nsplashimage /boot/grub/koolu_splash.xpm.gz' /target/boot/grub/menu.lst

# Koolu usplash -- cheap and nasty -- this should all be in a package
preseed_fetch $CHECKSUM_IF_AVAIL /classes/koolu/files/osdesktop-artwork.so.gz /target/usr/lib/usplash/osdesktop-artwork.so.gz
in-target gunzip /usr/lib/usplash/osdesktop-artwork.so.gz
rm /target/usr/lib/usplash/usplash-artwork.so
ln -s osdesktop-artwork.so /target/usr/lib/usplash/usplash-artwork.so
in-target update-initramfs -u

echo "debug: completed successfully"
