#!/bin/bash
#
# Copyright (c) 2005-2006 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details

MYNAME="uk/late_script"

log() {
    logger -t $MYNAME "$@"
}

echo 'd-i post-install "'$MYNAME'" from http://hands.com/d-i/'
log 'debug: running d-i post-install "'$MYNAME'" from http://hands.com/d-i/'

# KLUDGE LANG=  (really should work out what's wrong with the LANG=en thing)
sed -i -e 's/^LANG=.*$/LANG=C/' /target/etc/environment

# KLUDGE -- this should just work, but it doesn't so lets kick it in the head
echo Europe/London > /target/etc/timezone

log 'debug: '$MYNAME': exiting successfully'

exit 0
