#!/bin/sh
#
# Copyright (C) 2009 Hands.com Ltd
# Copyright (C) 2009 Luke Kenneth Casson Leighton <lkcl@lkcl.net>
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details
set -e

. /usr/share/debconf/confmodule
. /tmp/HandsOff-fn.sh

echo 'debug: Running...'

checkflag dbg/flags all-x tcproj/kludge-x && set -x

# FIXME -- this should be in a locally maintained package
preseed_fetch $CHECKSUM_IF_AVAIL classes/tcproj/kludge/files/etc.tgz /target/tmp/etc.tgz
in-target tar -C /etc -xozf /tmp/etc.tgz

apt-install hands-deb-keyring

echo 'debug: exiting successfully'
exit 0
