#!/bin/sh

in_local_class() {
    echo "$(debconf-get local/classes)" | sed -e 's/;/\n/g' | grep -q "^$1\$"
}

# tell anna to install an extra udeb
echo openssh-server-udeb >> /var/cache/anna/udeb_include

if in_local_class "sleeps" ; then
    sleep 10000 ; true
fi
