#!/bin/sh
# early_script of dbg class from http://hands.com/d-i/.../classes/dbg/early_script
#
# Copyright (c) 2011-2014 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details
#

# In this example, we run ./files/debug_lvm in the background so that it
# can await the creation of /lib/partman/lib/auto-lvm.sh and edit it
# before d-i runs it, allowing the test of a bug-fix.

# obviously, that script became pointless as soon as the bug was fixed.
# It is left here as an example.
 
. /usr/share/debconf/confmodule
. /tmp/HandsOff-fn.sh

preseed_fetch /classes/dbg/files/HandsOff-dbg-fn.sh /tmp/HandsOff-dbg-fn.sh
preseed_fetch /classes/dbg/files/debug_lvm /tmp/debug_lvm
chmod +x /tmp/debug_lvm

# drop this in the background so that it can wait for files to edit
/tmp/debug_lvm </dev/null >/dev/null 2>/dev/null &
