#!/bin/sh
#
# Copyright (c) 2005-2006 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details

set -e

. /usr/share/debconf/confmodule

if db_get base_install/base_excludes
then
	echo $RET | sed -e 's/,/\n/g' > /base_exclude

	# package to allow packages to be excluded from the base install
	BSW_VER=0.2
	preseed_fetch /udebs/bootstrapwrap_${BSW_VER}_all.udeb /tmp/bootstrapwrap_${BSW_VER}_all.udeb &&
		udpkg -i /tmp/bootstrapwrap_${BSW_VER}_all.udeb &&
		rm /tmp/bootstrapwrap_${BSW_VER}_all.udeb
fi
