#!/bin/sh
set -e

. /usr/share/debconf/confmodule

echo "debug: Running..."

# get rid of spurious lv
db_get partman-auto-lvm/new_vg_name &&
  lvremove -f /dev/$RET/keep_2

set -x
grep -q '/tmp' /target/etc/fstab ||
  echo "tmpfs   /tmp    tmpfs   size=512m,mode=1777     0       0" >> /target/etc/fstab
set +x

echo "debug: completed successfully"
