#!/bin/sh
#
# Copyright © 2012-2016 Daniel Dehennin <daniel.dehennin@baby-gnu.org>
#
# Distributed under the terms of the GNU GPL version 2 or (at your
# option) any later version see the file "COPYING" for details
#
set -e

. /tmp/HandsOff-fn.sh

echo "debug: Running..."

checkflag dbg/flags all-x net-x && set -x
virtual='virtual/net/interface/'

# Force netcfg/choose_interface
if classes | grep -q "${virtual}"; then
    # Only the last one
    preseed_interface=$(classes | sed -ne "\,${virtual}, s,^${virtual},,p" | tail -n 1)
    debconf-set 'netcfg/choose_interface' "${preseed_interface}"
    checkflag dbg/pauses all net && pause "Interface forced on “${preseed_interface}”"
fi
