#!/bin/sh

. /usr/share/debconf/confmodule
. /tmp/HandsOff-fn.sh

db_subst babelbox/info LANGNAME "Debian auto-install/Hands-off tutorial"
db_info babelbox/info

db_register hands-off/meta/text hands-off/pause/title
db_register hands-off/meta/text hands-off/pause

set_slide() {
  db_subst hands-off/pause/title DESC "$1"
  db_settitle hands-off/pause/title
  db_subst hands-off/pause DESCRIPTION "$2"
  db_input critical hands-off/pause
}

db_get debconf/language && lang="$RET"
preseed_fetch $CHECKSUM_IF_AVAIL "classes/tutorial/slides.$lang.txt" /tmp/slides.txt || preseed_fetch $CHECKSUM_IF_AVAIL classes/tutorial/slides.txt /tmp/slides.txt

SLIDE=1

while true; do
  [ 1 -eq $SLIDE ] && db_capb

  title=$(sed -ne 's/{'$SLIDE'} {\([^}]*\)}/\1/p' /tmp/slides.txt)
  if [ "$title" ] ; then
    set_slide "$title" "$(sed -e '1,/{'$SLIDE'} {[^}]*}/d' /tmp/slides.txt | sed -e '/{[0-9]*} {[^}]*}/,$d')"
  else
    # make sure we don't trash the newbies disk
    reboot
  fi

  if db_go; then
    SLIDE=$(($SLIDE + 1))
  else
    SLIDE=$(($SLIDE - 1))
    if [ $SLIDE -lt 1 ]; then
      exit 30
    fi
  fi
  db_capb backup
done

db_unregister hands-off/pause
db_unregister hands-off/pause/title

exit 0
