#!/bin/sh

# This script creates a generator that will add a local repository to the
# sources.list when apt-setup runs

mkdir -p /usr/lib/apt-setup/generators
cat > /usr/lib/apt-setup/generators/10local <<'!EOF!'
#!/bin/sh
set -e

. /usr/share/debconf/confmodule

# local/domain is set in local/preseed to avoid publishing it here
# this allows us to hardwire the domain independent of dhcp shinanegans
if db_get local/domain ; then
  domain=$RET
else
  db_get netcfg/get_domain
  domain=$RET
fi

file=$1

echo "deb http://debian-dsd-preseed.$domain/debian local-packages/" > $file
!EOF!
chmod +x /usr/lib/apt-setup/generators/10local
