#!/bin/sh

# if you add this to the kernel command line:  dbg/pauses=early
# then you can use this script by then switching to Alt-F2 and running:
#
#   preseed_fetch debug.sh /tmp/debug.sh
#   sh /tmp/debug.sh

# In this example, I'm patching one of the partman-lvm files, when it turns up
# to allow me to test a bug fix -- obviously, that won't work once the bug is
# fixed, but it shows the idea
 
. /usr/share/debconf/confmodule
. /tmp/HandsOff-fn.sh

preseed_fetch /classes/dbg/files/HandsOff-dbg-fn.sh /tmp/HandsOff-dbg-fn.sh
preseed_fetch /classes/dbg/files/debug_lvm /tmp/debug_lvm
chmod +x /tmp/debug_lvm

# drop this in the background so that it can wait for files to edit
/tmp/debug_lvm </dev/null >/dev/null 2>/dev/null &
