#!/bin/sh
#
# Copyright (c) 2007 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details

set -e
echo "debug: Running koolu/late_script..."
. /tmp/HandsOff-fn.sh

checkflag dbg/flags all-x koolu-x && set -x

apt-install linux-image-2.6.23.1-koolu

echo "debug: completed successfully"
