#!/bin/sh
#
# Copyright (c) 2005-2006 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details

MYNAME="classes/late_script"

. /usr/share/debconf/confmodule
. /tmp/HandsOff-fn.sh

log "debug: Running..."

# this is only needed for sarge installs, and not all of them
udpkg --configure apt-setup-udeb

db_register preseed/meta/text hands-off/title                                   db_register preseed/meta/text hands-off/item

db_subst hands-off/title DESC "Preseed late_script(s)"
db_progress START 0 $({ echo myself; classes; } | wc -w) hands-off/title

db_subst hands-off/item DESC "Running top level script"
db_progress INFO ai/meta/text2

# let's see what was installed by the end of the run (copied to /var/log/debian-installer/ along with the other log files)
cp /var/lib/dpkg/status /var/log/dpkg-status

# lock the root login if there's no password to set
# (has the side effect of shutting up the root password prompt)
if db_get passwd/root-password && [ -n "$RET" ]; then
  db_set passwd/root-password-again $RET
else
  pwfile=shadow
  db_get mirror/suite && [ sarge = "$RET" ] && pwfile=passwd

  sed -i -e 's#^root:[^:]*:#root:!:#' /target/etc/$pwfile
fi

# let's see if we're running under xen
if [ -e /proc/xen ] ; then
  mv /target/lib/tls /target/lib/tls.disabled
  # nasty hack, as we should probably install the kernel package
  cp -a /lib/modules/2.6.11-xenu /target/lib/modules/2.6.11-xenu
fi

# collect all class extra_pkgs files, and then apt-get the listed packages
# into the target
for class in $(classes); do
  prefix=classes/ ; expr "$class" : local/ >/dev/null && prefix=
  preseed_fetch "/${prefix}${class}/extra_pkgs" /tmp/extra_pkgs && \
    EXTRAPKGS="$EXTRAPKGS $(grep -v '^[ 	]*#' /tmp/extra_pkgs)"
  rm /tmp/extra_pkgs
done

if [ "$EXTRAPKGS" ]; then
  # FIXME -- should use apt-install here
  #chroot /target apt-get update
  #DEBIAN_FRONTEND=noninteractive chroot /target apt-get -y install $EXTRAPKGS
  apt-install $EXTRAPKGS
fi

### for debugging --- reenable the pre-reboot prompt
if in_class "dbg/late" ; then
  db_reset finish-install/reboot_in_progress
fi

db_progress STEP 1

# chain onto class specific late_script(s) if any
for class in $(classes); do
  db_subst hands-off/item DESC "Running script for class '$class'"
  db_progress INFO hands-off/item

  cl_a_ss=$(echo ${class}|sed 's/\([^-a-zA-Z0-9]\)/_/g')
  prefix=classes/ ; expr "$class" : local/ >/dev/null && prefix=
  preseed_fetch /${prefix}${class}/late_script /tmp/late_script-${cl_a_ss} && \
    sh /tmp/late_script-${cl_a_ss} > /var/log/late_script-${cl_a_ss}.out 2>&1
  db_progress STEP 1
done

db_progress STOP

db_unregister hands-off/title
db_unregister hands-off/item

log "debug: ended successfully"
