#!/bin/bash
#
# Copyright (c) 2005 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details

debconf-get() { echo GET $1 | debconf-communicate | cut -d ' ' -f 2 ; }

# the value of the server URL is passed in as parameter #1
DI_URL=$(debconf-get local/di-url)

# use the proxy for wgets (should speed things up)
export http_proxy=$(debconf-get mirror/http/proxy)

log() {
    logger -t install_script "$@"
}

echo 'debian-installer post-install "install_script" from http://hands.com/d-i/'
log 'debug: running debian-installer post-install "install_script" from http://hands.com/d-i/'

# I'm lazy -- this lets me run the commands needed to install a new xen domain without typing
cat > /root/.bash_history <<EOF
#dd if=/dev/zero of=/dev/hda count=1 ; sync ; reboot -f
xm create -c xm-debinst1-install
xm create -c xm-debinst1
EOF
chmod 600 /root/.bash_history

# FIXME -- should never get loaded in the first place
# don't need these
apt-get -y remove mdetect read-edid

# install ssh, and stop root login by password --- no race condition if root has no password :-)
apt-get -y install ssh
sed -i -e 's/^PermitRootLogin *yes/PermitRootLogin without-password/' /etc/ssh/sshd_config
/etc/init.d/ssh restart
# can set a root password here reasonably safely

# make sure we have md5sums for all packages we install
apt-get -y install debsums
cat >> /etc/apt/apt.conf <<!EOF!
DPkg::Post-Invoke {
        "debsums --generate=nocheck -sp /var/cache/apt/archives";
};
!EOF!

# nice stuff, even on a minmal box
apt-get -y install debconf-utils less udev sudo rsync debsums

# set LESSPIPE as I prefer
sed -i -e '/^  if \[ "$BASH" ]; then$/a\    . /etc/bash.bashrc' /etc/profile
echo "export LESSOPEN=\"|lesspipe '%s'\"" >> /etc/bash.bashrc

# Xen setup as inspired by: http://jclement.ca/xen/host_setup.html
# Xen requirements
apt-get -y install screen ssh debootstrap python python2.3-twisted iproute bridge-utils libcurl3-dev

XEN_VER=2.0.6
XEN_TGZ=xen-${XEN_VER}-install-x86_32.tgz
cd /root
#wget http://www.cl.cam.ac.uk/Research/SRG/netos/xen/downloads/${XEN_TGZ}
wget --progress=bar:force ${DI_URL}/misc/xen/${XEN_TGZ}
tar -xzvf ${XEN_TGZ}
cd xen-*-install
./install.sh

mv /lib/tls /lib/tls.disabled

# set grub to boot xen by default
ed /boot/grub/menu.lst 2>/dev/null <<EOF
/### BEGIN AUTOMAGIC KERNELS LIST/i
title Xen 2.0 / XenLinux 2.6.11.10
  kernel /boot/xen.gz dom0_mem=64000
  module /boot/vmlinuz-2.6-xen0 root=/dev/hda1 ro console=tty0

.
w
q
EOF

# set up boot time scripts
update-rc.d xend start 19 2 . stop 90 0 6 .
update-rc.d xendomains start 99 4 . stop 10 0 6 .

# this is recommended in the jclement's howto, but doesn't seem useful
# # setup network interfaces
# mv /etc/network/interfaces /etc/network/interfaces.orig
# cat >/etc/network/interfaces <<EOF
# # xen interfaces setup -- see /etc/xen/scripts/network
# auto lo eth0
# iface lo inet loopback
# iface eth0 inet static
#  address 0.0.0.0
#  netmask 255.255.255.255
# EOF

# get a kernel that lets us boot debian-installer under xen
wget --progress=bar:force ${DI_URL}/misc/xen/kernel-xen0-2.6.11-xenu_10.00.Custom_i386.deb -O /root/kernel-xen0-2.6.11-xenu_10.00.Custom_i386.deb
dpkg -i /root/kernel-xen0-2.6.11-xenu_10.00.Custom_i386.deb

# grab example xen configs
wget --progress=bar:force ${DI_URL}/misc/xen/xm-debinst1 -O /etc/xen/xm-debinst1
wget --progress=bar:force ${DI_URL}/misc/xen/xm-debinst1-install -O /etc/xen/xm-debinst1-install

# set up LVM on the spare partition
apt-get -y install lvm2
pvcreate /dev/hda6
vgcreate vg /dev/hda6
lvcreate -L 2G -n vm1hda vg

# make a directory for disk image files
mkdir /home/xen-disks
wget --progress=bar:force ${DI_URL}/misc/xen/netboot-initrd.gz -O /home/xen-disks/netboot-initrd.gz

# this allows local private stuff if needed
#wget ${DI_URL}/local/$(debconf-get local/type)_install_script -O /var/tmp/$(debconf-get local/type)_install_script
#bash /var/tmp/$(debconf-get local/type)_install_script

log 'debug: xen0-install_script exiting successfully'

# with luck we'll come back with xen running after the next reboot

# the temptation is to reboot the system now, but doing so in this
# script prevents the install from finishing properly, instead
# just tell people to hit Ctrl-Alt-DEL at the first login prompt

exit 0
