#!/bin/sh
#
# Copyright (c) 2005 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details

log() {
    logger -t late_script "$@"
}

log "debug: Running script from http://hands.com/d-i/site-files/default/type-files/xen0/preseed_late_script"
set -x

# First, unmount the redundant partition
umount /target/reserved-for-LVM

# then change the big partition's type to LVM
echo -e 't\n6\n8e\nw\nq' | fdisk /dev/discs/disc0/disc

# then get rid of the offending line in the fstab
sed -ie '/reserved-for-LVM/d' /target/etc/fstab

# and discard the redundant mountpount
rmdir /target/reserved-for-LVM

log "debug: xen0 script ended successfully"
