#!/bin/sh
#
# Copyright (C) 2005-2006 Hands.com Ltd
# Copyright (C) 2009 Luke Kenneth Casson Leighton <lkcl@lkcl.net>
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details
set -e

. /tmp/HandsOff-fn.sh

echo 'debug: Running...'

# time sync
apt-install ntpdate openntpd pkgsync bootsplash

echo 'debug: exiting successfully'
exit 0
