#!/bin/sh
#
# Copyright (C) 2005-2006 Hands.com Ltd
# Copyright (C) 2009 Luke Kenneth Casson Leighton <lkcl@lkcl.net>
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details
set -e

. /tmp/HandsOff-fn.sh

echo 'debug: Running...'

checkflag dbg/flags all-x tcproj-x && set -x

#eye candy
apt-install splashy splashy-themes hibernate
sed -i -e 's/ quiet/& vga=791 splash/' /target/boot/grub/menu.lst
sed -i -e 's/>default</>debian-moreblue</' /target/etc/splashy/config.xml
apt-install grub-splashimages
sed -i -e '/^color /a splashimage=(hd0,0)/grub/splashimages/debian-moreblue-swirl.xpm.gz' /target/boot/grub/menu.lst
in-target update-initramfs -u

# get rid of debug debris, if present
sed -i -e 's/ DEBCONF_DEBUG=[0-9][0-9]*//' /target/boot/grub/menu.lst

# time sync
apt-install ntpdate openntpd

echo 'debug: exiting successfully'
exit 0
