#!/bin/sh -e

# first update the checksum in preseed.cfg
checksigs_MD5=$(md5sum checksigs.sh|cut -d\  -f1)
sed -i '\#preseed/run/checksum#s#\(string[[:space:]]\+\)[[:alnum:]]\+$#\1'"${checksigs_MD5}"'#' preseed.cfg
start_MD5=$(md5sum start.sh|cut -d\  -f1)
sed -i '\#preseed/run/checksum#s#\(string[[:space:]]\+\)[[:alnum:]]\+$#\1'"${start_MD5}"'#' start.cfg

find ./ -name MD5SUMS\* -prune -o \( -type f -print0 \) | \
  sed -z -e 's#^\./##' | \
  xargs -0 md5sum > MD5SUMS

gpg --clearsign --personal-digest-preferences SHA256 MD5SUMS

rm MD5SUMS
