#!/bin/sh
#
# Copyright (c) 2007 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details
set -e
echo "debug: Running..."
echo "debug: completed successfully"
