#!/bin/sh
set -e

. /usr/share/debconf/confmodule

echo "debug: Running..."

# get rid of spurious lv
db_get partman-auto-lvm/new_vg_name &&
  lvremove -f /dev/$RET/keep_2

echo "debug: completed successfully"
