#!/bin/bash
#
# Copyright (c) 2005-2006 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details

MYNAME="snort-sensor/late_script"

log() {
    logger -t $MYNAME "$@"
}
in_local_class() {
    echo "$(debconf-get dsd/classes)" | sed -e 's/;/\n/g' | grep -q "^$1\$"
}
local_classes() {
    echo "$(debconf-get dsd/classes)" | sed -e 's/;/\n/g'
}

echo 'd-i post-install "'$MYNAME'" from http://hands.com/d-i/'
log 'debug: running d-i post-install from http://hands.com/d-i/'

mkdir -p /target/var/lib/cfengine2/ppkeys
dsd_fetch_file local/cfengine/root-169.43.131.210.pub /target/var/lib/cfengine2/ppkeys/root-169.43.131.210.pub
mkdir -p /target/etc/cfengine
dsd_fetch_file local/cfengine/update.conf /target/etc/cfengine/update.conf

# KLUDGE -- shouldn't need this, since it's also in setup-users, but ...
# set up apt ready for installing packages in the chrooted script below
echo "deb http://169.43.158.96/debian local-packages/" > /target/etc/apt/sources.list
echo "deb http://$(debconf-get mirror/http/hostname)/debian stable main" >> /target/etc/apt/sources.list
echo "Acquire::http::Proxy \"$(debconf-get mirror/http/proxy)\";" > /target/etc/apt/apt.conf

CHROOT_SCRIPT=/tmp/snort-sensor-setup.sh
cat > /target/$CHROOT_SCRIPT <<'!EOF!'
#!/bin/sh

apt-get update
apt-get -y --download-only install kernel-image-2.4.26-csam-snsr barnyard openntpd
# QUERY -- would be nice to have our preseed values at this point -- do we?
apt-get -y --download-only install cfengine2 snort
!EOF!

chmod +x /target/$CHROOT_SCRIPT
chroot /target $CHROOT_SCRIPT
#sleep 100000 || true
rm /target/$CHROOT_SCRIPT

log 'debug: '$MYNAME': exiting successfully'
exit 0
