#!/bin/bash
#
# Copyright (c) 2005-2006 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details

log() {
    logger -t install_script "$@"
}

echo 'debian-installer post-install "hands.com-general-tweaks/install_script" from http://hands.com/d-i/'
log 'debug: running debian-installer post-install "hands.com-general-tweaks/install_script" from http://hands.com/d-i/'

# make fsck automatically fix problems at boot time.
sed -i -e 's/^FSCKFIX=no/FSCKFIX=yes/' /etc/default/rcS

log 'debug: hands.com-general-tweaks/install_script exiting successfully'

exit 0
