#!/bin/bash
#
# Copyright (c) 2005 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details

# make fsck automatically fix problems at boot time.
sed -i -e 's/^FSCKFIX=no/FSCKFIX=yes/' /etc/default/rcS

debconf-get() { echo GET $1 | debconf-communicate | cut -d ' ' -f 2 ; }
debconf-fset() { echo FSET $@ | debconf-communicate ; }
debconf-set() { echo SET $@ | debconf-communicate ; }

# the value of the server URL is passed in as parameter #1
DI_URL=$(debconf-get local/di-url)

get_file() {
  if [ -n "$DI_URL" ] ; then
    wget ${DI_URL}/$1 -O $2
  else
    cp /hd-media/$1 $2
  fi
}

# use the proxy for wgets (should speed things up)
export http_proxy=$(debconf-get mirror/http/proxy)

log() {
    logger -t install_script "$@"
}

echo 'debian-installer post-install "install_script" from http://hands.com/d-i/'
log 'debug: running debian-installer post-install "install_script" from http://hands.com/d-i/'

# have to use unstable, because of thingy.  clamav.
cat >> /etc/apt/sources.list <<'EOF'

deb http://ftp.uk.debian.org/debian stable contrib non-free
deb http://security.debian.org stable/updates contrib non-free
deb http://ftp.uk.debian.org/debian unstable main contrib non-free
EOF
apt-get update

yes | apt-get -y install libc6

# install spamassassin, clamav and amavisd
apt-get -y install clamav clamav-daemon clamav-freshclam \
                   spamassassin libnet-dns-perl spamc amavisd-new

# enable spamassassin
sed -i -e 's/^ENABLED=0/ENABLED=1/' /etc/default/spamassassin

# make clamav possible to read amavis stuff
echo AllowSupplementaryGroups >> /etc/clamav/clamd.conf
usermod -G amavis clamav

# okay.  now we pin the damn packages to "stable".
# why we do this is because of damn clamav.
get_file dsd-subst/postfix-outgoing/files/preferences /etc/apt/preferences

# install postfix 
apt-get -y install postfix


# postfix and amavis configs
get_file dsd-subst/postfix-outgoing/amavisd.conf /etc/amavis/amavisd.conf
get_file dsd-subst/postfix-outgoing/files/master.cf /etc/postfix/master.cf
get_file dsd-subst/postfix-outgoing/files/main.cf /etc/postfix/main.cf
get_file dsd-subst/postfix-outgoing/files/aliases /etc/aliases

# install webmin and allow access from thingy.  internal network.
apt-get -y install webmin-postfix webmin-core webmin-spamassassin

sed -i -e 's/^allow=127.0.0.1/allow=127.0.0.1 172.20.0.0\/255.255.255.0 10.0.0.0\/255.0.0.0/' /etc/webmin/miniserv.conf

# install unpacking programs needed by amavis
apt-get -y install arc lha unarj unrar bzip2 lzop zoo

# restart servers
/etc/init.d/clamav-daemon restart
/etc/init.d/amavis restart
/etc/init.d/postfix reload
/etc/init.d/spamassassin restart
/etc/init.d/webmin restart

log 'debug: postfix-incoming-install_script exiting successfully'

exit 0
