#!/bin/sh
#
# Copyright (c) 2007 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details

set -e
echo "debug: Running koolu/late_script..."
. /usr/share/debconf/confmodule
. /tmp/HandsOff-fn.sh

checkflag dbg/flags all-x koolu-x && set -x

sed -ie 's/^# defoptions=.*/# defoptions=vga=791 splash quiet/' /target/boot/grub/menu.lst

apt-install linux-image-2.6.23.1-koolu \
  xserver-xorg-video-amd xserver-xorg discover libgl1-mesa-glx libgl1-mesa-dri libglu1-mesa \
  xfonts-base xfonts-100dpi xfonts-75dpi xfonts-scalable xterm alsa-base alsa-utils \
  xresprobe cpufrequtils vbetool menu discover xresprobe mdetect read-edid xutils binutils xpdf \
  usplash usplash-theme-debian

sed -ie '/Section "Device"/a\        Option "NoCompression" "true"' /target/etc/X11/xorg.conf

apt-install prelink

# Grub splash screen
preseed_fetch /classes/koolu/files/koolu_splash.xpm.gz /target/boot/grub/koolu_splash.xpm.gz
sed -ie '/^color/a \\nsplashimage /boot/grub/koolu_splash.xpm.gz' /target/boot/grub/menu.lst

# Koolu usplash -- cheap and nasty -- this should all be in a package
preseed_fetch /classes/koolu/files/osdesktop-artwork.so.gz /target/usr/lib/usplash/osdesktop-artwork.so.gz
in-target gunzip /usr/lib/usplash/osdesktop-artwork.so.gz
rm /target/usr/lib/usplash/usplash-artwork.so
ln -s osdesktop-artwork.so /target/usr/lib/usplash/usplash-artwork.so
in-target update-initramfs -u

echo "debug: completed successfully"
