#!/bin/sh
set -e

echo "debug: Running..."

apt-install xserver-xorg discover xserver-xorg-video-dummy libgl1-mesa-glx libgl1-mesa-dri libglu1-mesa xfonts-base xfonts-100dpi xfonts-75dpi xfonts-scalable iceweasel xterm alsa-base alsa-utils xresprobe cpufrequtils vbetool menu discover xresprobe mdetect read-edid xutils binutils

# kludge around the current lack of signature on the koolu packages
in-target apt-get -y --force-yes --no-remove install xserver-xorg-video-amd
in-target apt-get -y --force-yes --no-remove install linux-image-2.6.23.1-koolu

apt-install firefox x-ttcidfont-conf xprint  xprint-utils matchbox-window-manager

echo '7:23:respawn:/bin/login -f koolukiosk < /dev/tty7 > /dev/tty7' >> /target/etc/inittab

echo 'exec startx' >> /target/home/koolukiosk/.bash_profile

cat <<EOF > /target/home/koolukiosk/.xinitrc
xterm &
matchbox-window-manager -use_titlebar no &
firefox
EOF

echo "debug: completed successfully"
