#!/bin/sh
#
# Copyright (C) 2005-2006 Hands.com Ltd
# Copyright (C) 2009 Luke Kenneth Casson Leighton <lkcl@lkcl.net>
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details
set -e

. /tmp/HandsOff-fn.sh

echo 'debug: Running...'

checkflag dbg/flags all-x tcproj-x && set -x

# install all the required packages, as specified by pkgsync
apt-install pkgsync
in-target pkgsync
# Note: The list of packages should already be there, either via the tcproj/kludge
#       class, or via the package that should replace that soon

# prelink for speedier program startup
in-target prelink -aqR

# setup some  eye candy
sed -i 's/ quiet/& vga=791 splash/' /target/boot/grub/menu.lst
sed -i 's/>default</>debian-moreblue</' /target/etc/splashy/config.xml
sed -i '/^color /a splashimage=(hd0,0)/grub/splashimages/debian-moreblue-swirl.xpm.gz' /target/boot/grub/menu.lst
in-target update-initramfs -u

echo 'debug: exiting successfully'
exit 0
