#!/bin/sh
#
# Copyright (c) 2007 Luke Kenneth Casson Leighton <lkcl@lkcl.net>
#
# distributed under the terms of the GNU GPL version 2 or (at your option)
# any later version
# see the file "COPYING" for details
#

set -e

. /tmp/HandsOff-fn.sh

echo 'debug: Running...'

mkdir -p /target/etc/apt

cat >> /target/etc/apt/preferences <<!EOF!
Package: *
Pin: release a=stable
Pin-Priority: 900
Package: *
Pin: release a=testing
Pin-Priority: 800
!EOF!


