#!/bin/sh
#
# Copyright (c) 2005-2006 Hands.com Ltd
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details

# This script adds a nasty little hack to get round the fact that the soda
# installer needs to repartition the disk we're installing from, and that
# means we need to inmount things to allow partitioning to work properly
#
# This is really a painful-to-fix bug in partman

set -e

MYNAME="dsd/soda/early_script"

. /usr/share/dashslashdash/functions.sh

log "debug: Running..."
set -x

mkdir -p /lib/partman/commit.d
cat > /lib/partman/commit.d/29unmount-hda3 <<!EOF!
#!/bin/sh

umount /cdrom
umount /hd-media
!EOF!
db_get iso-scan/filename && isoname=$RET
cat > /lib/partman/commit.d/31mount-hda3 <<!EOF!
#!/bin/sh

mount -r /dev/discs/disc0/part3 /hd-media
mount -o loop,ro /hd-media/$isoname /cdrom
!EOF!
chmod +x /lib/partman/commit.d/*mount-hda3

log "debug: ends successfully"
